name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build binary
        run: make build

      - name: Run tests
        run: make test

      - name: Run linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest | export PATH=$PATH:$(go env GOPATH)/bin | make lint
