name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true

      - name: Build binary
        run: make build

      - name: Run tests
        run: make test

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "GOPATH: $(go env GOPATH)"
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          golangci-lint --version

      - name: Run linter with debug info
        run: |
          echo "PATH: $PATH"
          which golangci-lint
          make lint